default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ellink_dev

test:
  <<: *default
  database: ellink_test
production:
  <<: *default
  database: ellink_prod
  username: ellink
  password: <%= ENV['DATABASE_PASSWORD'] %>
